feat: Adds annotation support
SwissDataScienceCenter/calamus pull request #17
Opened 2020-05-22 12:32 UTC by Panaetius

Adds support for annotations.

Used like:

```
       import datetime.datetime as dt

       from calamus import JsonLDAnnotation
       import calamus.fields as fields

       schema = fields.Namespace("http://schema.org/")

       class User(metaclass=JsonLDAnnotation):
           class Meta:
               rdf_type = schema.Person
           _id = fields.Id()
           birth_date = fields.Date(schema.birthDate, default=dt.now)
           name = fields.String(schema.name, default=lambda: "John")

        user = User()

        # dumping
        User.schema().dump(user)
        # or
        user.dump()

        # loading
        u = User.schema().load({"_id": "http://example.com/user/1", "name": "Bill", "birth_date": "1970-01-01 00:00"})
```

Closes #3

2020-05-22 12:59 UTC, rokroskar commented
I don't understand the usage here - in your example does `User` become an annotation that you can add to other objects?

2020-05-22 13:09 UTC, Panaetius commented
No user is the object, but by declaring the attributes as calamus fields, the metaclass uses them to construct a Schema and returns the class with plain fields defined.

```
class User(metaclass=JsonLDAnnotation):
           class Meta:
               rdf_type = schema.Person
           _id = fields.Id(default=None)
           birth_date = fields.Date(schema.birthDate, default=dt.now)
```
gives you a class that looks like
```
class User:
    _id = None
    birth_date = dt.now
```
whose `.schema()` function returns a schema
```
class UserSchema:
    _id = fields.Id()
    birth_date = fields.Date(schema.birthDate)
    class Meta:
        model = User
        rdf_type = schema.Person
```

2020-05-23 00:35 UTC, rokroskar commented
Oops - I read "annotation" and immediately though of https://www.w3.org/ns/oa - very different annotation.

2020-09-25 14:35 UTC, rokroskar requested changes
This looks great! could you add an example to the readme?

2020-09-28 08:34 UTC, rokroskar approved these changes
Minor suggestion - feel free to ignore. 👍

2020-09-28 08:34 UTC, rokroskar commented on README.rst
> +        name = fields.String(schema.name, default=lambda: "John")
For ease of comparison, I would keep the ordering here the same as for `BookSchema` above:

```suggestion
        _id = fields.Id()
        birth_date = fields.Date(schema.birthDate, default=dt.now)
        name = fields.String(schema.name, default=lambda: "John")
        
        class Meta:
            rdf_type = schema.Person
```

2020-09-28 11:59 UTC, rokroskar submitted a review, later dismissed

2020-09-29 13:41 UTC, rokroskar approved these changes

2020-09-29 13:42 UTC, merged